---
- name: Install zsh
  become: true
  apt:
    name: zsh
    state: present

- name: Include oh-my-zsh
  include: oh-my-zsh.yml

- name: install autosuggestion plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

- name: Copy zsh config
  template:
    src: templates/zshrc.j2
    dest: ~/.zshrc
    mode: '0644'

- name: Set zsh as default shell
  user:
    name: "{{ zsh_user }}"
    shell: /bin/zsh
  become: true
  when: not zsh_shared

