---
# defaults file for virtualbox

## Virtualbox state
#
virtualbox_state: 'present'
#virtualbox_state: 'absent'
#virtualbox_state: 'reinstalled'
#virtualbox_state: 'purged'

virtualbox_version       : '5.2'
virtualbox_install_dkms  : no               # default for 5.1 as no longer required

virtualbox_apt_key_url_1 : 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
virtualbox_apt_key_url_2 : 'https://www.virtualbox.org/download/oracle_vbox.asc'
virtualbox_apt_repo      : 'deb http://download.virtualbox.org/virtualbox/debian xenial contrib'
# Debian 8 jesse
#virtualbox_apt_repo      : 'deb http://download.virtualbox.org/virtualbox/debian jessie contrib'
virtualbox_apt_pkg       : 'virtualbox-5.2'
virtualbox_apt_dkms_pkg  : 'virtualbox-dkms'
