---
- name: Install
  become: yes
  apt:
    name: terminator
    state: latest
    update_cache: yes

- name: Ensure config directory exist
  file:
    path: ~/.config/terminator
    state: directory

- name: Copy config
  template:
    src: templates/config.j2
    dest: ~/.config/terminator/config
    mode: '0664'