---
- name: Copy config
  template:
    src: templates/cinnamon_config.j2
    dest: ~/cinnamon_config.dconf
    mode: '0664'

- name: Restore config
  shell: dconf load /org/cinnamon/ < ~/cinnamon_config.dconf
  args:
    executable: /bin/bash