---
- name: Ensure themes directory exist
  file:
    path: ~/.themes
    state: directory

- name: Download and unpack theme
  unarchive:
    src: https://cinnamon-spices.linuxmint.com/files/themes/Numix-Cinnamon-Transparent.zip
    dest: ~/.themes
    remote_src: yes

- name: Copy config
  template:
    src: templates/cinnamon_config.j2
    dest: ~/cinnamon_config.dconf
    mode: '0664'

- name: Restore config
  shell: dconf load /org/cinnamon/ < ~/cinnamon_config.dconf
  args:
    executable: /bin/bash