---
- name: Add key
  become: yes
  apt_key:
    url: "https://download.spotify.com/debian/pubkey.gpg"
    state: present

- name: Add repository
  become: yes
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    filename: spotify

- name: Run apt-get update
  become: yes
  apt:
    update_cache: yes

- name: Install
  become: yes
  apt:
    name: spotify-client
    state: latest