---
- name: Add key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
    state: present

- name: Add repository
  become: yes
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    filename: spotify

- name: Install Spotify
  apt:
    name: spotify-client
    state: latest