---
python_required_packages:
    - software-properties-common
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip

# you complete me 
ycm_packages:
    - build-essential
    - cmake
