---
# tasks file for vim
  tasks:

  - name: Add some repo
    yum:
      name: epel-release
      state: present
      tags:
      - vim

  - name: Install vim
    yum:
      name: vim
      state: present
      tags:
      - vim
~             
