---
- name: Add repository
  become: yes
- apt_repository:
    repo: ppa:linuxuprising/shutter

- name: Run apt-get update
  become: yes
  apt:
    update_cache: yes

- name: Install
  become: yes
  apt:
    name: shutter
    state: latest