---
- name: Install dependencies
  become: true
  apt:
    name: "{{ python_required_packages }}"
    state: present

- name: Install you complete me dependencies
  become: true
  apt:
    name: "{{ ycm_packages }}"
    state: present

- name: Install
  become: yes
  apt:
    name: neovim
    state: latest

- name: use nvim for vim
  alternatives: name=vim path=/usr/bin/nvim

- name: use nvim for editor
  become: true
  alternatives: name=editor path=/usr/bin/nvim
